# -*- coding: utf-8 -*-
'''
>File Name      :MyPractise.py
>Author         :Tridu33
>Created Time   :2019/10/3 17:30:34
'''
from manimlib.imports import *
class StableState(Scene):
    def construct(self):
        quote = Text("稳态平衡的意义",font='Source Han Sans',size=0.5)
        quote.set_color(RED)
        quote.to_edge(UP)
        quote2 = Text("谈谈马尔可夫链模型三种等价解法理解",font='Source Han Sans',size=0.5)
        quote2.set_color(BLUE)
        author=Text("---Tridu33")
        author.scale(0.5)
        author.next_to(quote.get_corner(DOWN+RIGHT),DOWN)
        img1 = r'C:\Users\admin\Documents\Tridu33\!Py\!3b1b-video\manim\manimlib\files\Statement.png'
        imMob1 = ImageMobject(img1)  # Makes an image mobject of existing image
        imMob1.scale(3)
        imMob1.shift(UP)
        flowtext0 =Text("X1, X2, X3公司现阶段市场现占比30%，40%，30%",font='Source Han Sans',size=0.5)
        flowtext0.to_edge(DOWN)
        flowtext1 = Text("本月购买X1者下月购买X1, X2, X3的概率0.75 0.2 0.05",font='Source Han Sans',size=0.5)
        flowtext1.to_edge(DOWN)
        flowtext2 = Text("本月购买X2者下月购买X1, X2, X3的概率0.1 0.7 0.2",font='Source Han Sans',size=0.5)
        flowtext2.to_edge(DOWN)
        flowtext3 = Text("本月购买X3者下月购买X1, X2, X3的概率0.1 0.1 0.8",font='Source Han Sans',size=0.5)
        flowtext3.to_edge(DOWN)
        self.add(quote)
        self.add(author)
        self.wait(2)
        self.play(Transform(quote,quote2),
          ApplyMethod(author.move_to,quote2.get_corner(DOWN+RIGHT)+DOWN+2*LEFT))
        self.play(ApplyMethod(author.scale,1.5))
        author.match_color(quote2)
        self.play(FadeOut(quote))
        self.remove(author)
        self.play(FadeIn(imMob1))
        # 这里是闪现状态转换解说过程
        self.play(Write(flowtext0))
        self.wait(1)
        self.remove(flowtext0)
        self.play(Write(flowtext1))
        self.wait(1)
        self.remove(flowtext1)
        self.play(Write(flowtext2))
        self.wait(1)
        self.remove(flowtext2)
        self.play(Write(flowtext3))
        self.wait(1)
        self.remove(flowtext3)
        self.remove(imMob1)
        imMob2=imMob1.scale(0.5)
        imMob2.shift(2*UP+4*LEFT)
        self.add(imMob2)
        self.play(FadeInFrom(imMob2, DOWN))
        eq1=Text(r'''概率转移矩阵:''',font='Source Han Sans',size=0.5) 
        eq2=Text("0.75 0.2 0.05",font='Source Han Sans',size=0.5)
        eq3=Text("0.1  0.7 0.2 ",font='Source Han Sans',size=0.5)
        eq4=Text("0.1  0.1 0.8 ",font='Source Han Sans',size=0.5)
        eq1.shift(UP+4*LEFT)
        eq2.shift(4*LEFT)
        eq3.shift(1*DOWN+4*LEFT)
        eq4.shift(2*DOWN+4*LEFT)
        eq5=TexMobject(r"sum_{i=1}^3{x_i=1}")
        eq5.shift(3*DOWN+4*LEFT)
        self.play(Write(eq1))
        self.play(Write(eq2))
        self.play(Write(eq3))
        self.play(Write(eq4))
        self.play(Write(eq5))
        #1
        text1=Text(r'''法一(状态转移矩阵无穷幂定值):''',font='Source Han Sans',size=0.5) 
        text1.shift(3*UP+RIGHT)
        eq11=TexMobject("S_0=[0.3\ 0.4\ 0.3]")
        eq12=TexMobject("S_{(i+1)}=S_0*P^i")
        eq13=TexMobject("S_0*P^\infty")
        text2=Text(r'''稳态X1,X2,X3占比:''',font='Source Han Sans',size=0.5) 
        eq14=TexMobject("[0.28571\ 0.32143\ 0.39286]")
        eq11.shift(2*UP)
        eq12.shift(UP)
        text2.shift(DOWN+RIGHT)
        eq14.shift(2*DOWN+0.5*RIGHT)
        self.play(Write(text1))
        self.play(Write(eq11))
        self.play(Write(eq12))
        self.play(Write(eq13))
        self.play(Write(text2))
        self.play(Write(eq14))
        self.remove(text1,text2,eq11,eq12,eq13,eq14)
        #2
        text1=Text(r'''法二(稳态下X占比不变):''',font='Source Han Sans',size=0.5) 
        text1.shift(3*UP+RIGHT)
        eq11=TexMobject("0.75x_1+0.1+0.1x_3=x_1")
        eq12=TexMobject("0.2x_1+0.7x_2+0.1=x_2")
        eq13=TexMobject("0.05x_1+0.2x_2+0.8x_3=x_3")
        eq14=TexMobject(r"sum_{i=1}^3{x_i=1}")
        text2=Text(r'''解方程稳态X1,X2,X3占比:''',font='Source Han Sans',size=0.5) 
        eq15=TexMobject("[0.28571\ 0.32143\ 0.39286]")
        eq11.shift(2*UP+RIGHT)
        eq12.shift(UP+RIGHT)
        eq13.shift(1.2*RIGHT)
        eq14.shift(2*DOWN+RIGHT)
        text2.shift(DOWN+RIGHT)
        eq15.shift(3*DOWN+RIGHT)
        self.play(Write(text1))
        self.play(Write(eq11))
        self.play(Write(eq12))
        self.play(Write(eq13))
        self.play(Write(text2))
        self.play(Write(eq14))
        self.remove(text1,text2,eq11,eq12,eq13,eq14,eq15)
        #3
        text1=Text(r'''法三(类基尔霍夫出=入，法二移项）:''',font='Source Han Sans',size=0.5) 
        text1.shift(3*UP+2*RIGHT)
        eq11=TexMobject("0.2x_1+0.05x_1=0.1x_3+0.1x_2")
        eq12=TexMobject("0.1x_2+0.2x_2=0.2x_1+0.1x_3")
        eq13=TexMobject("0.1x_3+0.1x_3=0.05x_1+0.2x_2")
        eq14=TexMobject(r"sum_{i=1}^3{x_i=1}")
        text2=Text(r'''解方程稳态X1,X2,X3占比:''',font='Source Han Sans',size=0.5) 
        eq15=TexMobject("[0.28571\ 0.32143\ 0.39286]")
        eq11.shift(2*UP+1.5*RIGHT)
        eq12.shift(UP+1.5*RIGHT)
        eq13.shift(1.5*RIGHT)
        eq14.shift(2*DOWN+1.5*RIGHT)
        text2.shift(DOWN+RIGHT)
        eq15.shift(3*DOWN+RIGHT)
        self.play(Write(text1))
        self.play(Write(eq11))
        self.play(Write(eq12))
        self.play(Write(eq13))
        self.play(Write(text2))
        self.play(Write(eq14))
        self.remove(text1,text2,eq11,eq12,eq13,eq14,eq15)








